/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BContainer: typeof import('bootstrap-vue-next/components/BContainer')['BContainer']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BuildingView: typeof import('./src/components/BuildingView.vue')['default']
    HomeView: typeof import('./src/components/HomeView.vue')['default']
    MapView: typeof import('./src/components/MapView.vue')['default']
    Navigation: typeof import('./src/components/Navigation.vue')['default']
    NewBuildingView: typeof import('./src/components/NewBuildingView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    VillageInfo: typeof import('./src/components/VillageInfo.vue')['default']
  }
}
